const messages = {
  EN: {
    company_name: "Wvmee",
    login: "Login",
    sign_up: "Sign up",
    email_address: "Email",
    name: "Name",
    password: "Password",
    confirm_password: "Confirm Password",
    forgot_password: "Forgot Password",
    already_account: "Already have an account?",
    no_account: "Don't have an account yet?",
    organiser: "Organiser",
    user: "User",
    guest: "Guest",
    admin: "Admin",
    attendee: "Attendee",
    accept: "I accept the",
    tnc: "Terms and Conditions",
    processing: "Processing",
    delete_meeting: "Delete Meeting?",
    delete_meeting_caption: "Are you sure you want to delete this meeting?",
    yes: "Yes",
    no: "No",
    home: "Home",
    today_meetings: "Today's Meetings",
    scheduled_meetings: "Scheduled Meetings",
    join: "Join",
    watch_recording: "Watch Recording",
    new_meeting: "New Meeting",
    create_meeting: "Create a new meeting",
    add_title: "Add Title",
    choose_start_time: "Choose Start Time",
    choose_end_time: "Choose End Time",
    select: "Select",
    excel_import: "Excel Import",
    description: "Write a summary about the meeting",
    cancel: "Cancel",
    update: "Update",
    save: "Save",
    edit_profile: "Edit Profile",
    translate: "Translate",
    log_out: "Log Out",
    recordings: "Recordings",
    recording_caption: "There is the latest updated recordings",
    play: "Play",
    days_ago: "days ago",
    attendance: "Attendance",
    attendance_caption: "There is the latest updated attendance",
    view_attendance: "View Attendance",
    title: "Title",
    start_time: "Start Time",
    end_time: "End Time",
    action: "Action",
    no_records: "No Records found",
    duration: "Duration",
    save_profile: "Save Profile",
    profile: "Profile",
    select_role: "Select Role",
    set_up: "Set Up Your Meeting Room",
    setup_caption:
      "Total Control, Total Impact: Managing Camera, Video, Speaker, and Configuration for Your Pre-launch Meeting.",
    select_camera: "Select your camera device",
    select_microphone: "Select your microphone",
    settings: "Settings",
    camera: "Camera",
    microphone: "Microphone",
    leave: "Leave",
    screen_share: "Screen Share",
    record: "Record",
    recording_saved: "Recording Saved",
    whiteboard: "Whiteboard",
    documents: "Documents",
    participants: "Participants",
    chat: "Chat",
    full_screen: "Full Screen",
    tile_view: "Tile View",
    type_message: "Type message",
    mute_all: "Mute All",
    captions: "Captions",
    confirm: "Confirm",
    add: "Add",
    ok: "Ok",
    vid_quality: "Video Quality",
    something_went_wrong: "Something went wrong",
    document_del_wrong: "Something went wrong while deleting document",
    document_upload_wrong: "Something went wrong while uploading documents",
    document_get_wrong: " Something went wrong while getting documents",
    attendance_went_wrong: "Something went wrong while getting attendance",
    conf_went_wrong:
      "Something went wrong while validating conference. Please try again",
    record_save_wrong: "Something went wrong When Save Your Recording",
    not_invited:
      "You are not invited to this meeting. Request permission to send an invitation to join the meeting.",
    copy_right: "Copyright",
    all_rights_reserved: "All Rights Reserved",
    terms_and_conditions: "Terms And Conditions",
    privacy_policy: "Privacy Policy",
    other_device_warning:
      "It looks like you are in this call from another device. Please leave from there to join the meeting on this device.",
    admit_list: "Lobby Admit List",
  },
  JAP: {
    company_name: "うわーみー",
    login: "ログイン",
    sign_up: "サインアップ",
    email_address: "メールアドレス",
    name: "名前",
    password: "パスワード",
    confirm_password: "パスワードの確認",
    forgot_password: "パスワードをお忘れですか",
    already_account: "すでにアカウントをお持ちですか？",
    no_account: "まだアカウントをお持ちでないですか？",
    organiser: "主催者",
    guest: "ゲスト",
    user: "ユーザー",
    admin: "管理者",
    attendee: "参加者",
    accept: "私は受け入れます",
    tnc: "利用規約",
    processing: "処理中",
    delete_meeting: "会議を削除しますか?",
    delete_meeting_caption: "本当にこのミーティングを削除しますか?",
    yes: "はい",
    no: "いいえ",
    home: "ホーム",
    today_meetings: "今日のミーティング",
    scheduled_meetings: "予定されたミーティング",
    join: "参加する",
    watch_recording: "録画を見る",
    new_meeting: "新しいミーティング",
    create_meeting: "新しいミーティングを作成する",
    add_title: "タイトルを追加",
    choose_start_time: "開始時刻を選択",
    choose_end_time: "終了時刻を選択",
    select: "選択",
    excel_import: "Excel インポート",
    description: "ミーティングの要約を書く",
    cancel: "キャンセル",
    update: "更新",
    save: "保存",
    edit_profile: "プロフィールを編集",
    translate: "翻訳",
    log_out: "ログアウト",
    recordings: "録画",
    recording_caption: "最新の更新された録画があります",
    play: "再生",
    days_ago: "日前",
    attendance: "出席",
    attendance_caption: "最新の更新された出席があります",
    view_attendance: "出席を表示",
    title: "タイトル",
    start_time: "開始時刻",
    end_time: "終了時刻",
    action: "アクション",
    no_records: "レコードが見つかりません",
    duration: "期間",
    save_profile: "プロフィールを保存",
    profile: "プロフィール",
    select_role: "役割を選択",
    set_up: "ミーティングルームの設定",
    setup_caption:
      "トータルコントロール、トータルインパクト：事前のミーティングのためにカメラ、ビデオ、スピーカー、および構成を管理します。",
    select_camera: "カメラデバイスを選択",
    select_microphone: "マイクロフォンを選択",
    settings: "設定",
    camera: "カメラ",
    microphone: "マイクロフォン",
    leave: "退出",
    screen_share: "画面共有",
    record: "記録",
    whiteboard: "ホワイトボード",
    documents: "ドキュメント",
    participants: "参加者",
    chat: "チャット",
    full_screen: "フルスクリーン",
    tile_view: "タイル表示",
    type_message: "メッセージを入力",
    mute_all: "全員をミュート",
    captions: "キャプション",
    confirm: " 確認",
    add: "追加",
    ok: "OK",
    vid_quality: "ビデオ品質",
    something_went_wrong: "何らかの問題が発生しました",
    document_del_wrong: "ドキュメントの削除中に問題が発生しました",
    document_upload_wrong: "ドキュメントのアップロード中に問題が発生しました",
    document_get_wrong: "ドキュメントの取得中に問題が発生しました",
    attendance_went_wrong: "出席の取得中に問題が発生しました",
    conf_went_wrong:
      "会議の検証中に問題が発生しました。もう一度やり直してください",
    record_save_wrong: "録音を保存するときに問題が発生しました",
    not_invited:
      "この会議には招待されません。会議に参加するための招待状を送信する許可を要求します。",
    copy_right: "著作権",
    all_rights_reserved: "無断転載を禁じます",
    terms_and_conditions: "利用規約",
    privacy_policy: "プライバシーポリシー",
    other_device_warning:
      "別のデバイスからこの通話に参加しているようです。このデバイスで会議に参加するには、退出してください。",
    admit_list: "ロビーアドレミート",
  },
};
let langCode = localStorage.getItem("lang") || "EN";
let constant = messages[langCode];
const switchLanguage = (lang) => {
  localStorage.setItem("lang", lang);
  constant = messages[lang];
  window.location.reload();
};

let routes = {
  home: "/",
  signup: "/signup",
  error: "/error",
  tnc: "/terms-and-conditions",
  meeting_list: "/meetinglist",
  attendance: "/attendence",
  whiteboard: "/whiteboard",
  mailsend: "/mailsend",
  verify: "/verify",
  calendar: "/calendar",
  edit_profile: "/editprofile",
  reset_password: "/resetpassword",
  forgot_password: "/forgotpassword",
  admin: "/admin",
  screen_recording: "/screen",
  documentupload: "/documentupload",
  recorder: "/recorder",
  meeting_room: "/meet",
  record: "/recordings",
  guest: "/guest",
  face_login: "/face-login",
  face_register: "/face-register",
};

let apiRoutes = {
  home: "/",
  register: "/register/registerUser",
  verifyUser: "/register/verifyUser",
  guest_register: "/register/registerAsGuest",
  admin_register: "/register/registerByAdmin",
  login: "/users/login",
  error: "/error",
  tnc: "/terms-and-conditions",
  meeting_list_by_id: "/meeting/getMeetingById",
  meeting_room_by_id: "/meeting/getMeetingByRoomId",
  logout: "/register/logout",
  meeting_save: "/meeting/saveMeeting",
  delete_meeting: "/meeting/deleteMeeting",
  forgot_password: "/register/forgetPassword",
  all_users: "/users/getAllUsers",
  user_delete: "/users/deleteUser",
  all_meeting_get: "/meeting/getAllMeetingList",
  get_meeting_by_date: "/meeting/getMeetingListByDate",
  get_meeting_by_week: "/meeting/getMeetingListByWeek",
  get_meeting_by_month: "/meeting/getMeetingListByMonth",
  meeting_update: "/meeting/updateMeeting",
  userStatus: "/users/getUserStatus",
  validateRoom: "/meeting/validateMeeting",
  attendance_time: "/attendance/addAttendanceTime",
  chat_add: "/chat/sendMessage",
  chat_get: "/chat/getMessages",
  document_upload: "/document/uploadDocument",
  document_get: "/document/getDocumentsByMeetingId",
  document_delete: "/document/deleteDocument",
  recording_get_by_user: "/document/getDocumentsByUserId",
  attendance_get_by_meeting: "/attendance/getAttendanceByMeetingId",
  attendance_get: "/attendance/getAttendance",
  edit_profile: "/users/editUser",
  get_user_by_email: "/users/getUserByEmail",
  upload_photo: "/document/uploadProfilePhoto",
  whiteboard: "/whiteboard",
  mailsend: "/mailsend",
  verify: "/verify",
  calendar: "/calendar",
  excel_add: "/document/addExcelData",
  terms_and_conditions_upload: "/register/uploadTermsAndCondition",
  terms_and_conditions_get: "/register/getTermsAndCondition",

  reset_password: "/register/resetPassword",
  //forgot_password: "/forgotpassword",
  admin: "/admin",
  screen_recording: "/screen-recording",

  recorder: "/recorder",
  meeting_room: "/meet",
  record: "/recordings",
  getTnC: "/register/getTermsAndCondition",
  uploadTnC: "/register/uploadTermsAndCondition",
};

export { constant, routes, apiRoutes, switchLanguage };
